config/routes.rb
Rails.application.routes.draw do
  get '/about', to: "static_pages#about"
  get '/services', to: "static_pages#services"
  get '/contact', to: "static_pages#contact"
  get '/promotion', to: "static_pages#promotion"
  resources :categories, only: [:show]
  resources :reviews
  resources :line_items
  resources :carts
  get 'products/index'
  get 'products/show'
  devise_for :users, controllers: {
  	registrations: 'registrations' , omniauth_callbacks: 'users/omniauth_callbacks'
  }


  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products,       only: [:index, :show]
  resources :payments
  resources :search_results, only: [:index]
  resources :users
  resources :messages, only: [:create]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_product(product)
		current_item = line_items.find_by(product_id: product.id)
		if current_item
			current_item.increment(:quantity)
		else
			current_item = line_items.build(product_id: product.id)
		end 
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price } 
	end 
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy

	def self.search(search)
		all.where("lower(name) LIKE :search", search: "%#{search}%")
	end 
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price.to_i * quantity.to_i
  end 
end

app/models/message.rb
class Message < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true
	validates :message, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user

  VALID_NUMBER = /\A2376\d{8}\z/i
  	validates :phone, :presence => {:message => 'hello world, bad operation!'},
  					length: { maximum: 13 },
                    format: { with: VALID_NUMBER }
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :line_items, dependent: :destroy
	has_many :reviews, dependent: :destroy

	def self.search(search)
		all.where("lower(title) LIKE :search", search: "%#{search}%")
	end 

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/transaction.rb
class Transaction
	include HTTParty
	base_uri "https://api.monetbil.com/payment/v1/placePayment"
	
	def self.pay(phone, amount)
		post("", body: { 
			service: "u7mFjGzx5Gn8UVMHYFgJgJP4oxNRMcXR",
			phonenumber: "#{phone}",
			amount: "#{amount}",
			notify_url: "http://localhost3000.org/monetbil/notifications"
		}.to_json)
	end
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  has_many :payments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image# assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end



  # rubocop:disable Lint/AssignmentInCondition
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(session[:cart_id])
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attemp to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user_transactions = current_user.payments
	end

	def edit
    	@user = current_user
  	end 

  	def update
    	@user = current_user
	    if @user.update_attributes(update_params)
	      flash[:success] = "Profile successfully updated"
	      redirect_to @user
	    else
	      render 'edit'
	    end
	end

	private

	def update_params
		params.require(:user).permit(:name, :email, :phone_number)
	end 


end 

app/helpers/application_helper.rb
module ApplicationHelper

	def cart_count_over_one
		if @cart.line_items.count > 0
			return "<span class='tag is-dark'>#{@cart.line_items.count}</span>".html_safe
		end
	end

	def cart_has_items
		return @cart.line_items.count > 0
	end

	def list_category
		return Category.all
	end 
	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="container-fluid cart-show">
	<div class="row justify-content-center">
		<%= link_to 'Keep Shopping', products_path, id: "keep-shoping-link" %>
	</div>
	
	<div id="inner-card" class="container">
			<% @cart.line_items.each do |line_item| %>
				<div class="row cart-show-row-grid text-center">
					<div class="col-3 mx-auto test">
						<h4 class="">Product</h4>
						<%= image_tag(line_item.product.photo_link, style: "width: 100px;") %>
						<p class=""><%= line_item.product.title %></p>
					</div>
					<div class="col-3 mx-auto test">
						<h4 class="">quantity</h4>
						<p class=""><%= line_item.quantity %></p>
					</div>
					<div class="col-3 mx-auto test">
						<h4 class="">amount</h4>
						<p class=""><%= number_to_currency(line_item.total_price) %></p>
					</div>
					<div class="col-3 mx-auto test">
						<%= link_to "Remove Item", line_item, method: :delete, data: { confirm: "Are you sure? "}, id: "remove-item-button" %>
					</div>	
				</div>
			<div class="card-division"></div>
		<% end %>
	</div>

	<div class="total-amount-div container d-flex justify-content-between mt-4">
		<h4 class="text-white"><span>Total : </span><%= @cart.total_price %> frs</h4>
		<%= button_to "Empty Cart", @cart, method: :delete, data: { confirm: "Are you sure? "}, class: "button is-danger" %> 
	</div>

	<div class="container payment-method-div mt-5">
		<h2 class="payment-method-div-content text-center" id="paywith-text" >Pay With =></h2>
		<%= link_to image_tag("https://res.cloudinary.com/it-s-tech/image/upload/v1580604458/ci.mtn.mtnmobilemoney_a83fse.jpg", class: "payment-photo"), new_payment_path, class: "payment-method-div-content" %>

		<%= link_to image_tag("https://res.cloudinary.com/it-s-tech/image/upload/v1580604458/orange-money_lquhcg.jpg", class: "payment-photo"),new_payment_path, class: "payment-method-div-content" %>
	</div>

</div>