config/routes.rb
Rails.application.routes.draw do
  get '/about', to: "static_pages#about"
  get '/services', to: "static_pages#services"
  get '/contact', to: "static_pages#contact"
  get '/promotion', to: "static_pages#promotion"
  resources :categories, only: [:show]
  resources :reviews
  resources :line_items
  resources :carts
  get 'products/index'
  get 'products/show'
  devise_for :users, controllers: {
  	registrations: 'registrations' , omniauth_callbacks: 'users/omniauth_callbacks'
  }


  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products,       only: [:index, :show]
  resources :payments
  resources :search_results, only: [:index]
  resources :users
  resources :messages, only: [:create]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_product(product)
		current_item = line_items.find_by(product_id: product.id)
		if current_item
			current_item.increment(:quantity)
		else
			current_item = line_items.build(product_id: product.id)
		end 
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price } 
	end 
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy

	def self.search(search)
		all.where("lower(name) LIKE :search", search: "%#{search}%")
	end 
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price.to_i * quantity.to_i
  end 
end

app/models/message.rb
class Message < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true
	validates :message, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user

  VALID_NUMBER = /\A2376\d{8}\z/i
  	validates :phone, :presence => {:message => 'hello world, bad operation!'},
  					length: { maximum: 13 },
                    format: { with: VALID_NUMBER }
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :line_items, dependent: :destroy
	has_many :reviews, dependent: :destroy

	def self.search(search)
		all.where("lower(title) LIKE :search", search: "%#{search}%")
	end 

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/transaction.rb
class Transaction
	include HTTParty
	base_uri "https://api.monetbil.com/payment/v1/placePayment"
	
	def self.pay(phone, amount)
		post("", body: { 
			service: "u7mFjGzx5Gn8UVMHYFgJgJP4oxNRMcXR",
			phonenumber: "#{phone}",
			amount: "#{amount}",
			notify_url: "http://localhost3000.org/monetbil/notifications"
		}.to_json)
	end
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  has_many :payments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image# assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end



  # rubocop:disable Lint/AssignmentInCondition
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base
	before_action :authenticate_user!, only: %i[create]


	def create
		@review = current_user.reviews.build(review_params)
		if @review.save
			flash[:success] = "Thanks for the review #{current_user.name} and happy shopping"
			redirect_back(fallback_location: @review.product)
		else
			flash[:alert] = "Review form can't be submited while empty"
			redirect_back(fallback_location: @review.product)
		end
	end

  private

    def review_params
      params.require(:review).permit(:product_id, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def cart_count_over_one
		if @cart.line_items.count > 0
			return "<span class='tag is-dark'>#{@cart.line_items.count}</span>".html_safe
		end
	end

	def cart_has_items
		return @cart.line_items.count > 0
	end

	def list_category
		return Category.all
	end 
	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_form.html.erb
	<%= simple_form_for(@review) do |f| %>
  	<%= f.error_notification %>
  	<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

	  <div class="form-inputs">
	    <%= f.input :product_id, :as => :hidden, :input_html => { :value => @product.id } %>
	    <%= f.input :content, label: false, placeholder: "Write a short review for this product." %>
	  </div>

	  <div class="form-actions">
	    <%= f.button :submit, "Review", id: "review-button", class: "font-weight-bold" %>
	  </div>
	<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user %></td>
        <td><%= review.product %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>