config/routes.rb
Rails.application.routes.draw do
  get '/about', to: "static_pages#about"
  get '/services', to: "static_pages#services"
  get '/contact', to: "static_pages#contact"
  get '/promotion', to: "static_pages#promotion"
  resources :categories, only: [:show]
  resources :reviews
  resources :line_items
  resources :carts
  get 'products/index'
  get 'products/show'
  devise_for :users, controllers: {
  	registrations: 'registrations' , omniauth_callbacks: 'users/omniauth_callbacks'
  }


  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products,       only: [:index, :show]
  resources :payments
  resources :search_results, only: [:index]
  resources :users
  resources :messages, only: [:create]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_product(product)
		current_item = line_items.find_by(product_id: product.id)
		if current_item
			current_item.increment(:quantity)
		else
			current_item = line_items.build(product_id: product.id)
		end 
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price } 
	end 
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy

	def self.search(search)
		all.where("lower(name) LIKE :search", search: "%#{search}%")
	end 
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price.to_i * quantity.to_i
  end 
end

app/models/message.rb
class Message < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true
	validates :message, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user

  VALID_NUMBER = /\A2376\d{8}\z/i
  	validates :phone, :presence => {:message => 'hello world, bad operation!'},
  					length: { maximum: 13 },
                    format: { with: VALID_NUMBER }
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :line_items, dependent: :destroy
	has_many :reviews, dependent: :destroy

	def self.search(search)
		all.where("lower(title) LIKE :search", search: "%#{search}%")
	end 

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/transaction.rb
class Transaction
	include HTTParty
	base_uri "https://api.monetbil.com/payment/v1/placePayment"
	
	def self.pay(phone, amount)
		post("", body: { 
			service: "u7mFjGzx5Gn8UVMHYFgJgJP4oxNRMcXR",
			phonenumber: "#{phone}",
			amount: "#{amount}",
			notify_url: "http://localhost3000.org/monetbil/notifications"
		}.to_json)
	end
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  has_many :payments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image# assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end



  # rubocop:disable Lint/AssignmentInCondition
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def cart_count_over_one
		if @cart.line_items.count > 0
			return "<span class='tag is-dark'>#{@cart.line_items.count}</span>".html_safe
		end
	end

	def cart_has_items
		return @cart.line_items.count > 0
	end

	def list_category
		return Category.all
	end 
	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<div class="container-fluid mt-3">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %> 
      <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="site-footer text-white pt-5">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="row">
              <div class="col-5">
                <h6 class="footer-heading mb-4">About Us</h6>
                <p style="font-size: 0.7em;">Quality services and products at affordable prices</p>
              </div>
              <div class="col-3 ">
                <h6 class="footer-heading mb-4">Quick Links</h6>
                <ul style="font-size: 0.7em;" class="list-unstyled">
                  <li><%= link_to "About us", about_path, class: "footer-link" %></li>
                  <li><%= link_to "Our Services", services_path, class: "footer-link" %></li>
                  <li><%= link_to "About us", contact_path, class: "footer-link" %></li>
                </ul>
              </div>
              <div class="col-4">
                <h6 class="footer-heading mb-4">Follow Us</h6>
                <ul class="list-unstyled">
                  <li class="mb-5"><a href="https://www.instagram.com/juicii_enterprise/" class="footer-icon" target="_blank"><i class="fab fa-facebook fa-2x"></i></a></li>
                  <li><a href="https://www.facebook.com/JuiciiEnterprise/" target="_blank" class="footer-icon"><i class="fab fa-instagram fa-2x"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-3 ml-auto">
            <h6 class="footer-heading mb-4">Juicii Enterprise</h6>
            <a href="#"><img src="https://res.cloudinary.com/it-s-tech/image/upload/v1580598779/20200131_232003_0000_nuovas.png" alt="Image" class="img-fluid mb-3"></a>
            <p style="font-size: 0.7em;">We help you win!!</p>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
            <p>
              Copyright &copy;2020 All rights reserved | This website is maintained <i class="icon-heart" aria-hidden="true"></i> by <a href="https://itstech.herokuapp.com" target="_blank" >Group-Itstech</a>
            </p>
            </div>
          </div>         
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<section class="header-third-layer overlay bg-danger">
  <div class="container header-third-layer-div">
    <div class="row header-third-layer-div align-items-center justify-content-center">

      <div class="col-md-12" data-aos="fade-up" data-aos-delay="400">
                    
        <div class="row mb-4">
          <div class="col-md-7">
            <h1 class="text-center">Shop With Us</h1>
            <p class="mb-5 lead text-center">We always serve you the best deals at affordable prices.</p>
            <div>
              <a href="#our-products" class="btn header-btn py-3 px-5 rounded-0 mb-lg-0 mb-2 d-block d-sm-inline-block">Shop Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>  

app/views/layouts/_navbar.html.erb
<section id="first-header-section">
    <div class="container first-header-section-div">
        <div class="social-media-icons-div">
            <ul>
                <li><a class="social-media-icons" href="https://www.facebook.com/JuiciiEnterprise/" target="_blank"><i class="fab fa-facebook fa-2x"></i></a></li>
                <li><a class="social-media-icons" href="https://www.instagram.com/juicii_enterprise/" class="footer-icon" target="_blank"><i class="fab fa-instagram fa-2x"></i></a></li>
            </ul>
        </div>
        <div id="first-layer-contact-div">
            <ul>
                <li><a href="#" class="first-layer-contact"><i class ="fa fa-phone right-icons"></i><span class="d-none d-md-inline">+237672349428</span></a></li>
                <li><a href="#" class="first-layer-contact"><i class ="fa fa-phone right-icons"></i><span class="d-none d-md-inline">+237650757572</span></a></li>
                <li><a href="#" class="first-layer-contact"><i class="fa fa-envelope right-icons"></i><span class="d-none d-md-inline">juiciienterprise@gmail.com</span></a></li>
            </ul>
        </div>
    </div>
</section>
    <nav class="navbar navbar-expand-lg bg-white sticky-top">
        <div class="container-fluid">
            <a style="width: 5%;" class="d-none d-md-block navbar-brand text-dark p-0" href="/"><img src="https://res.cloudinary.com/it-s-tech/image/upload/v1580598779/20200131_232003_0000_nuovas.png" atl="logo-pic" id="logo-pic"></a>
            <a style="width: 20%;" class="d-md-none navbar-brand text-dark p-0" href="/"><img src="https://res.cloudinary.com/it-s-tech/image/upload/v1580598779/20200131_232003_0000_nuovas.png" atl="logo-pic" id="logo-pic"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon bg-dark"></span>
            </button>
            <div style="width: 20%;" id="create-space" class="d-none d-md-block">sdf</div>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <div class="d-none d-md-block">
                  <%= simple_form_for :search, url: search_results_path, method: "GET", html: { class: "form-inline text-center" } do |f| %>

                      <%= f.input :search, label: false, placeholder: "search a product" %>
                      <%= f.submit "Search", id: "navbar-search-button", class: "btn"%>
                  <% end %>
                </div>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active d-md-none">                    
                        <%= simple_form_for :search, url: search_results_path, method: "GET", html: { class: "form-inline text-center" } do |f| %>

                            <%= f.input :search, label: false, placeholder: "search a product" %>
                            <%= f.submit "Search", id: "navbar-search-button", class: "btn"%>
                        <% end %>
                   </li>
                   <li class="nav-item">
                        <%= link_to("Products", root_path, class: "nav-link text-dark") %>
                    </li>                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Product category</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <% list_category.each do |category| %>
                                <%= link_to category.name, category, class: "h5 p-3" %><br/>
                            <% end %>
                        </div>
                    </li>       
                    <% if user_signed_in? %>
                    <li class="nav-item active">
                        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link text-dark" %>
                    </li>
                    <li class="nav-item active">
                        <%#= link_to "Dashboard", current_user, class: "nav-link text-dark" %>
                    </li>
                    <% else %>
                    <li class="nav-item active">
                        <a href="/promotion" class="nav-link text-dark">Promotions</a>
                    </li>
                    <li class="nav-item active">
                        <%= link_to "sign in", new_user_session_path, class: "nav-link text-dark" %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to "create account", new_user_registration_path, class: "nav-link text-dark" %>
                    </li>
                    <% end %>
                    <li class="nav-item">
                        <%= link_to("About", about_path, class: "nav-link text-dark") %>
                    </li>
                    <li class="nav-item">
                        <%= link_to("Services", services_path, class: "nav-link text-dark") %>
                    </li>
                    <li class="nav-item">
                        <%= link_to("Contact", contact_path, class: "nav-link text-dark") %>
                    </li>
                    <% if cart_has_items %>
                    <li class="nav-item active">
                      <%= link_to cart_path(@cart) do %>
                        <span class="icon is-small">
                          <i class="fa fa-shopping-cart"></i>
                        </span>
                        <span>Cart
                          <%= cart_count_over_one %>
                        </span>
                      <% end %>
                    </li>
                  <% end %>
                    
                </ul>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuiciiStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Juicii store is an ecommerce platform where you can get all your house hold utilities" %>">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash_messages" %> 
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</html>